from collections.abc import Callable, Sequence
from typing import Any

class FuzzedDataProvider:
    # Store fuzz bytes for later provider reads. Inputs: data. Output: None.
    def __init__(self, data: bytes) -> None: ...
    # Return a bounded fuzz integer. Inputs: minimum, maximum. Output: int.
    def ConsumeIntInRange(self, minimum: int, maximum: int) -> int: ...
    # Return fuzz text without surrogates. Inputs: count. Output: str.
    def ConsumeUnicodeNoSurrogates(self, count: int) -> str: ...

# Configure the fuzz harness. Inputs: argv, test_one_input. Output: None.
def Setup(argv: Sequence[str], test_one_input: Callable[[bytes], object]) -> None: ...

# Start fuzz execution. Inputs: none. Output: None.
def Fuzz() -> None: ...

# Return a dynamic attribute. Inputs: name. Output: Any.
def __getattr__(name: str) -> Any: ...
