from collections.abc import Callable, Sequence
from typing import Any

class FuzzedDataProvider:
    def __init__(self, data: bytes) -> None: ...
    def ConsumeIntInRange(self, minimum: int, maximum: int) -> int: ...
    def ConsumeUnicodeNoSurrogates(self, count: int) -> str: ...

def Setup(argv: Sequence[str], test_one_input: Callable[[bytes], object]) -> None: ...
def Fuzz() -> None: ...
def __getattr__(name: str) -> Any: ...
