from typing import Any

class Connection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> Connection: ...
    def __exit__(self, *args: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
