from typing import Any

class Connection:
    # Create the typed stub object. Inputs: *args, **kwargs. Output: None.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    # Enter the context manager. Inputs: none. Output: Connection.
    def __enter__(self) -> Connection: ...
    # Exit the context manager. Inputs: *args. Output: None.
    def __exit__(self, *args: Any) -> None: ...
    # Return a dynamic attribute. Inputs: name. Output: Any.
    def __getattr__(self, name: str) -> Any: ...
