#!/usr/bin/env bash
# ============================================================================
# Entrypoint for the pg-maintenance container.
#
# Cron does not inherit the container environment reliably. Write the required
# runtime settings into a private, shell-quoted env file, then install the static
# cron schedule that invokes pg-maintenance through the cron runner.
# ============================================================================

set -euo pipefail

ENV_FILE="${PG_MAINTENANCE_ENV_FILE:-/etc/pg-maintenance-env}"
CRON_FILE="${PG_MAINTENANCE_CRON_FILE:-/etc/cron.d/pg-maintenance}"
LOG_FILE="${PG_MAINTENANCE_LOG_FILE:-/var/log/pg-maintenance.log}"

REQUIRED_ENV_VARS=(
    OMERO_DB_HOST
    OMERO_DB_PORT
    OMERO_DB_NAME
    OMERO_DB_USER
    OMERO_DB_PASS
    PLUGIN_DB_HOST
    PLUGIN_DB_PORT
    PLUGIN_DB_NAME
    PLUGIN_DB_USER
    PLUGIN_DB_PASS
)

OPTIONAL_ENV_VARS=(
    PATH
    TZ
    PGTZ
    PG_MAINTENANCE_LOCK_TIMEOUT
    PG_MAINTENANCE_VACUUM_STATEMENT_TIMEOUT
    PG_MAINTENANCE_REINDEX_STATEMENT_TIMEOUT
)

log() { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')" "$*"; }

die() { log "FATAL: $*" >&2; exit 1; }

derive_runtime_env_aliases() {
    if [ -z "${PLUGIN_DB_PASS:-}" ] && [ -n "${OMP_PLUGIN_DB_PASS:-}" ]; then
        export PLUGIN_DB_PASS="${OMP_PLUGIN_DB_PASS}"
    fi
}

write_export() {
    local name="$1"
    local value="${!name-}"

    printf 'export %s=' "$name"
    printf '%q' "$value"
    printf '\n'
}

write_cron_env() {
    local missing=()
    local tmp_file
    local name

    derive_runtime_env_aliases
    for name in "${REQUIRED_ENV_VARS[@]}"; do
        if [ -z "${!name:-}" ]; then
            missing+=("$name")
        fi
    done
    if (( ${#missing[@]} )); then
        die "Missing required environment variables: ${missing[*]}"
    fi

    umask 077
    tmp_file="$(mktemp "${ENV_FILE}.XXXXXX")" || die "Could not create temporary env file for ${ENV_FILE}"

    if ! {
        printf '# Generated by pg-maintenance-entrypoint.sh. Do not edit.\n'
        for name in "${REQUIRED_ENV_VARS[@]}"; do
            write_export "$name"
        done
        for name in "${OPTIONAL_ENV_VARS[@]}"; do
            if [ -n "${!name:-}" ]; then
                write_export "$name"
            fi
        done
    } > "$tmp_file"; then
        rm -f "$tmp_file"
        die "Could not write temporary env file for ${ENV_FILE}"
    fi

    chmod 0600 "$tmp_file" || {
        rm -f "$tmp_file"
        die "Could not restrict permissions on temporary env file for ${ENV_FILE}"
    }
    mv -f "$tmp_file" "$ENV_FILE" || {
        rm -f "$tmp_file"
        die "Could not install ${ENV_FILE}"
    }
}

main() {
    if [ "$(id -u)" -ne 0 ]; then
        die "pg-maintenance entrypoint must run as root so it can install cron and write ${ENV_FILE}"
    fi

    write_cron_env
    crontab "$CRON_FILE"

    log "pg-maintenance container started."
    log "Cron schedule loaded. Maintenance will run automatically."
    log "- VACUUM ANALYZE : every Sunday at 03:00"
    log "- REINDEX CONCUR.: first Sunday of month at 04:00"
    log "Run manually:  docker exec pg-maintenance pg-maintenance.sh all"
    printf '\n'

    cron
    exec tail -F "$LOG_FILE"
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main "$@"
fi
