name: security-code-scanning

on:
  pull_request:
    branches:
      - main
      - alpha
  push:
    branches:
      - main
      - alpha
  schedule:
    - cron: '23 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

concurrency:
  group: security-code-scanning-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql:
    name: CodeQL (${{ matrix.language }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        language:
          - python
          - javascript-typescript

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: /language:${{ matrix.language }}

  trivy-filesystem:
    name: Trivy filesystem scan (SARIF)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif
          scanners: vuln,misconfig,secret
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: trivy-fs

  fortify:
    name: Fortify AST Scan
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write # Required for PR comments

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Fortify Scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
          debricked-sca-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PASSWORD: ${{ secrets.FOD_PAT }}
          DO_EXPORT: true
          DO_PR_COMMENT: true
          DO_JOB_SUMMARY: true
