repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: aab412d509121cb5f7533134b7e67f9fab59c682 # v0.16.4
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]
