[mypy]
mypy_path = typings
show_error_codes = True
pretty = False
warn_unused_configs = True
check_untyped_defs = True
no_implicit_optional = True
strict_equality = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True
