[supervisord]
nodaemon=true

[program:omero-web]
command=/opt/omero/web/%(ENV_OMERO_WEB_VENV)s/bin/gunicorn --config /opt/omero/web/OMERO.web/gunicorn.conf.py OMERO.web.wsgi:application
directory=/opt/omero/web/OMERO.web
autostart=true
autorestart=true
stderr_logfile=/opt/omero/web/logs/supervisord.err.log
stdout_logfile=/opt/omero/web/logs/supervisord.out.log
