from typing import Any

class ClientError(Exception): ...
class SecurityViolation(Exception): ...

class client:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

scripts: Any
sys: Any
rtypes: Any

def __getattr__(name: str) -> Any: ...
