from typing import Any

class _GatewayObject:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class BlitzGateway(_GatewayObject): ...
class FileAnnotationWrapper(_GatewayObject): ...

class ColorHolder(_GatewayObject):
    @classmethod
    def fromRGBA(cls, red: int, green: int, blue: int, alpha: int) -> ColorHolder: ...
    def getHtml(self) -> str: ...
