from typing import Any

class _GatewayObject:
    # Create the typed stub object. Inputs: *args, **kwargs. Output: None.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    # Return a dynamic attribute. Inputs: name. Output: Any.
    def __getattr__(self, name: str) -> Any: ...

class BlitzGateway(_GatewayObject): ...
class FileAnnotationWrapper(_GatewayObject): ...

class ColorHolder(_GatewayObject):
    @classmethod
    # Return from RGBA. Inputs: red, green, blue, alpha. Output: ColorHolder.
    def fromRGBA(cls, red: int, green: int, blue: int, alpha: int) -> ColorHolder: ...
    # Return HTML. Inputs: none. Output: str.
    def getHtml(self) -> str: ...
