from typing import Any

class _GridColumn:
    # Initialize the instance. Inputs: *args, **kwargs. Output: None.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    # Return a dynamic attribute. Inputs: name. Output: Any.
    def __getattr__(self, name: str) -> Any: ...

class DoubleColumn(_GridColumn): ...
class LongColumn(_GridColumn): ...
