from typing import Any

class _GridColumn:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class DoubleColumn(_GridColumn): ...
class LongColumn(_GridColumn): ...
