from typing import Any

# Return rbool. Inputs: value. Output: Any.
def rbool(value: Any) -> Any: ...

# Return rdouble. Inputs: value. Output: Any.
def rdouble(value: Any) -> Any: ...

# Return rint. Inputs: value. Output: Any.
def rint(value: Any) -> Any: ...

# Return rlong. Inputs: value. Output: Any.
def rlong(value: Any) -> Any: ...

# Return robject. Inputs: value. Output: Any.
def robject(value: Any) -> Any: ...

# Return rstring. Inputs: value. Output: Any.
def rstring(value: Any) -> Any: ...

# Return rtime. Inputs: value. Output: Any.
def rtime(value: Any) -> Any: ...

# Return a dynamic attribute. Inputs: name. Output: Any.
def __getattr__(name: str) -> Any: ...
