from typing import Any

def rbool(value: Any) -> Any: ...
def rdouble(value: Any) -> Any: ...
def rint(value: Any) -> Any: ...
def rlong(value: Any) -> Any: ...
def robject(value: Any) -> Any: ...
def rstring(value: Any) -> Any: ...
def rtime(value: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
