from typing import Any

class ParametersI:
    # Initialize the instance. Inputs: *args, **kwargs. Output: None.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    # Add. Inputs: *args, **kwargs. Output: ParametersI.
    def add(self, *args: Any, **kwargs: Any) -> ParametersI: ...
    # Add ID. Inputs: *args, **kwargs. Output: ParametersI.
    def addId(self, *args: Any, **kwargs: Any) -> ParametersI: ...
    # Return exp. Inputs: *args, **kwargs. Output: ParametersI.
    def exp(self, *args: Any, **kwargs: Any) -> ParametersI: ...
    # Return a dynamic attribute. Inputs: name. Output: Any.
    def __getattr__(self, name: str) -> Any: ...

class Principal:
    # Initialize the instance. Inputs: *args, **kwargs. Output: None.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    # Return a dynamic attribute. Inputs: name. Output: Any.
    def __getattr__(self, name: str) -> Any: ...
