from typing import Any

class ParametersI:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add(self, *args: Any, **kwargs: Any) -> ParametersI: ...
    def addId(self, *args: Any, **kwargs: Any) -> ParametersI: ...
    def exp(self, *args: Any, **kwargs: Any) -> ParametersI: ...
    def __getattr__(self, name: str) -> Any: ...

class Principal:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
