from typing import Any

class GZip:
    # Create the typed stub object. Inputs: *args, **kwargs. Output: None.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    # Return encode. Inputs: data. Output: bytes.
    def encode(self, data: bytes) -> bytes: ...
    # Decode the encoded value. Inputs: data. Output: bytes.
    def decode(self, data: bytes) -> bytes: ...

# Return codec. Inputs: spec. Output: Any.
def get_codec(spec: Any) -> Any: ...

# Return a dynamic attribute. Inputs: name. Output: Any.
def __getattr__(name: str) -> Any: ...
