from typing import Any

class GZip:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def encode(self, data: bytes) -> bytes: ...
    def decode(self, data: bytes) -> bytes: ...

def get_codec(spec: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
