from typing import Any

class BaseContainer:
    image: Any
    well: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class BaseShare:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

def getIntOrDefault(*args: Any, **kwargs: Any) -> Any: ...
def load_metadata_preview(*args: Any, **kwargs: Any) -> Any: ...
def render_response(*args: Any, **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
