from typing import Any

class _OMEROObject:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class DatasetI(_OMEROObject): ...
class FileAnnotationI(_OMEROObject): ...
class ImageAnnotationLinkI(_OMEROObject): ...
class LengthI(_OMEROObject): ...
class MapAnnotationI(_OMEROObject): ...
class NamedValue(_OMEROObject): ...
class OriginalFileI(_OMEROObject): ...
class ProjectDatasetLinkI(_OMEROObject): ...
class ProjectI(_OMEROObject): ...

def __getattr__(name: str) -> Any: ...
