from typing import Any

class _OMEROObject:
    # Initialize the instance. Inputs: *args, **kwargs. Output: None.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    # Return a dynamic attribute. Inputs: name. Output: Any.
    def __getattr__(self, name: str) -> Any: ...

class DatasetI(_OMEROObject): ...
class FileAnnotationI(_OMEROObject): ...
class ImageAnnotationLinkI(_OMEROObject): ...
class LengthI(_OMEROObject): ...
class MapAnnotationI(_OMEROObject): ...
class NamedValue(_OMEROObject): ...
class OriginalFileI(_OMEROObject): ...
class ProjectDatasetLinkI(_OMEROObject): ...
class ProjectI(_OMEROObject): ...

# Return a dynamic attribute. Inputs: name. Output: Any.
def __getattr__(name: str) -> Any: ...
