from typing import Any

# Return prepared image. Inputs: *args, **kwargs. Output: Any.
def _get_prepared_image(*args: Any, **kwargs: Any) -> Any: ...

# Render thumbnail. Inputs: *args, **kwargs. Output: Any.
def _render_thumbnail(*args: Any, **kwargs: Any) -> Any: ...

# Return Int Or Default. Inputs: *args, **kwargs. Output: Any.
def getIntOrDefault(*args: Any, **kwargs: Any) -> Any: ...

# Return longs. Inputs: *args, **kwargs. Output: Any.
def get_longs(*args: Any, **kwargs: Any) -> Any: ...

# Return thumbnails JSON. Inputs: *args, **kwargs. Output: Any.
def get_thumbnails_json(*args: Any, **kwargs: Any) -> Any: ...

# Return image Data JSON. Inputs: *args, **kwargs. Output: Any.
def imageData_json(*args: Any, **kwargs: Any) -> Any: ...

# Return jsonp. Inputs: *args, **kwargs. Output: Any.
def jsonp(*args: Any, **kwargs: Any) -> Any: ...

# Render image. Inputs: *args, **kwargs. Output: Any.
def render_image(*args: Any, **kwargs: Any) -> Any: ...

# Render image region. Inputs: *args, **kwargs. Output: Any.
def render_image_region(*args: Any, **kwargs: Any) -> Any: ...

# Return a dynamic attribute. Inputs: name. Output: Any.
def __getattr__(name: str) -> Any: ...
