from typing import Any

def _get_prepared_image(*args: Any, **kwargs: Any) -> Any: ...
def _render_thumbnail(*args: Any, **kwargs: Any) -> Any: ...
def getIntOrDefault(*args: Any, **kwargs: Any) -> Any: ...
def get_longs(*args: Any, **kwargs: Any) -> Any: ...
def get_thumbnails_json(*args: Any, **kwargs: Any) -> Any: ...
def imageData_json(*args: Any, **kwargs: Any) -> Any: ...
def jsonp(*args: Any, **kwargs: Any) -> Any: ...
def render_image(*args: Any, **kwargs: Any) -> Any: ...
def render_image_region(*args: Any, **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
