#!/usr/bin/env bash
# =============================================================================
# install-quota-enforcer.sh — Install the OMERO host-side quota enforcer
#
# Sets up systemd timer + service for ext4 project-quota enforcement.
# Compatible with Ubuntu 24.04+ and Debian 13 (Trixie)+.
#
# Usage:
#   sudo ./install-quota-enforcer.sh /path/to/OMERO/data
#
# Example:
#   sudo ./install-quota-enforcer.sh /data/OMERO
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_SYSTEM_DIR="${SYSTEMD_SYSTEM_DIR:-/etc/systemd/system}"
SYSTEMCTL_BIN="${SYSTEMCTL_BIN:-systemctl}"
DEFAULTS_FILE="${OMERO_QUOTA_DEFAULTS_FILE:-/etc/default/omero-quota-enforcer}"

# shellcheck source=scripts/omero-host-service-lib.sh
source "${SCRIPT_DIR}/omero-host-service-lib.sh"

usage() {
    echo "Usage: $0 <OMERO_DATA_DIR>" >&2
    echo "  OMERO_DATA_DIR: Path to the OMERO data directory on the host" >&2
    echo "                  (same as OMERO_USER_DATA_PATH in installation_paths.env)" >&2
}

render_unit() {
    local source_file="$1"
    local dest_file="$2"

    omero_render_systemd_unit \
        "${source_file}" \
        "${dest_file}" \
        DEFAULTS_FILE "${defaults_file}" \
        ENFORCER_PATH "${enforcer_dst}" \
        OMERO_DATA_DIR "${OMERO_DATA_DIR}" \
        QUOTA_STATE_FILE "${state_file}"
}

replace_managed_units() {
    omero_replace_systemd_units \
        "${SYSTEMCTL_BIN}" \
        "${SYSTEMD_SYSTEM_DIR}" \
        omero-quota-enforcer.timer \
        omero-quota-enforcer.path \
        omero-quota-enforcer.service
}

install_required_packages() {
    omero_install_missing_deb_packages e2fsprogs quota python3 util-linux
}

verify_project_quota_support() {
    local fs_type mount_point block_device mount_options

    IFS=$'\t' read -r fs_type mount_point block_device mount_options \
        < <(omero_mount_context "${OMERO_DATA_DIR}")

    if [[ "${fs_type}" != "ext4" ]]; then
        echo "  WARNING: Filesystem is '${fs_type}', not ext4." >&2
        echo "  Project quotas only work on ext4. Continuing installation." >&2
        return 0
    fi

    if omero_mount_options_include "${mount_options}" prjquota \
        || omero_mount_options_include "${mount_options}" project; then
        echo "  Filesystem at ${mount_point} is mounted with project quotas."
    else
        echo "  WARNING: Filesystem at ${mount_point} is not mounted with prjquota." >&2
        echo "  Add 'prjquota' to /etc/fstab and remount:" >&2
        echo "    sudo mount -o remount,prjquota ${mount_point}" >&2
        echo "  Continuing installation." >&2
    fi

    if [[ "${block_device}" = /dev/* ]] && command -v tune2fs >/dev/null 2>&1; then
        if tune2fs -l "${block_device}" 2>/dev/null | grep -q "Filesystem features:.*project"; then
            echo "  ext4 'project' feature is enabled on ${block_device}."
        else
            echo "  WARNING: ext4 'project' feature is not enabled on ${block_device}." >&2
            echo "  Enable it with: sudo tune2fs -O project ${block_device}" >&2
        fi
    fi
}

install_enforcer_script() {
    local enforcer_src src_sha256

    enforcer_src="${SCRIPT_DIR}/omero-quota-enforcer.sh"
    OMERO_INSTALLATION_PATH="${OMERO_INSTALLATION_PATH:-${SCRIPT_DIR%/}/..}"
    OMERO_INSTALLATION_PATH="$(readlink -f -- "${OMERO_INSTALLATION_PATH}")"
    enforcer_dst="${OMERO_INSTALLATION_PATH%/}/scripts/omero-quota-enforcer.sh"

    src_sha256="$(omero_install_verified "${enforcer_src}" "${enforcer_dst}" 0755)"
    echo "  Installed: ${enforcer_dst} (sha256=${src_sha256})"
}

write_defaults_file() {
    local quoted_data_dir quoted_managed_root quoted_min_quota
    local quoted_project_id_min quoted_projects_file quoted_projid_file quoted_state_file

    defaults_file="${DEFAULTS_FILE}"
    if [[ -f "${defaults_file}" ]]; then
        echo "  ${defaults_file} already exists; preserving existing configuration."
        return 0
    fi

    quoted_data_dir="$(omero_environment_quote "${OMERO_DATA_DIR}")"
    quoted_state_file="$(omero_environment_quote "${OMERO_DATA_DIR}/.admin-tools/group-quotas.json")"
    quoted_managed_root="$(omero_environment_quote "${OMERO_DATA_DIR}/ManagedRepository")"
    quoted_projects_file="$(omero_environment_quote "${OMERO_DATA_DIR}/.admin-tools/quota/projects")"
    quoted_projid_file="$(omero_environment_quote "${OMERO_DATA_DIR}/.admin-tools/quota/projid")"
    quoted_project_id_min="$(omero_environment_quote "200000")"
    quoted_min_quota="$(omero_environment_quote "0.10")"

    install -d -m 0755 "$(dirname -- "${defaults_file}")"
    cat > "${defaults_file}" <<DEFAULTS
# OMERO Quota Enforcer configuration
# Generated by install-quota-enforcer.sh on $(date -Iseconds)

# Path to the OMERO data directory on the host
OMERO_DATA_DIR=${quoted_data_dir}

# Quota state JSON (written by omeroweb container, read by this enforcer)
QUOTA_STATE_FILE=${quoted_state_file}

# Managed repository root
MANAGED_REPO_ROOT=${quoted_managed_root}

# Project-ID mapping files
PROJECTS_FILE=${quoted_projects_file}
PROJID_FILE=${quoted_projid_file}
PROJECT_ID_MIN=${quoted_project_id_min}

# Minimum quota value in GB
MIN_QUOTA_GB=${quoted_min_quota}
DEFAULTS
    echo "  Created: ${defaults_file}"
}

prepare_admin_tools_dir() {
    mkdir -p "${OMERO_DATA_DIR}/.admin-tools/quota"
    # The .admin-tools directory must be writable by both:
    # - the host-side enforcer (root)
    # - the omeroweb container (non-root)
    #
    # DO NOT use sticky-bit (1777) here: it can break atomic replace (os.replace)
    # if group-quotas.json ownership differs from the current writer UID.
    # Use 0777 (world-writable, no sticky) to allow safe atomic updates.
    chmod 0777 "${OMERO_DATA_DIR}/.admin-tools"
    chmod 0777 "${OMERO_DATA_DIR}/.admin-tools/quota"

    # Ensure the quota state file remains writable for the non-root omeroweb
    # container user even when this installer is executed as root during upgrades.
    state_file="${OMERO_DATA_DIR}/.admin-tools/group-quotas.json"
    if [[ -f "${state_file}" ]]; then
        chmod 0666 "${state_file}"
    else
        install -m 0666 /dev/null "${state_file}"
    fi

    echo "  Created: ${OMERO_DATA_DIR}/.admin-tools/ (mode 0777)"
    echo "  Ensured writable quota state: ${state_file} (mode 0666)"
}

install_systemd_units() {
    local service_dst timer_dst path_dst

    service_dst="${SYSTEMD_SYSTEM_DIR%/}/omero-quota-enforcer.service"
    timer_dst="${SYSTEMD_SYSTEM_DIR%/}/omero-quota-enforcer.timer"
    path_dst="${SYSTEMD_SYSTEM_DIR%/}/omero-quota-enforcer.path"

    replace_managed_units
    render_unit "${SCRIPT_DIR}/omero-quota-enforcer.service" "${service_dst}"
    install -D -m 0644 "${SCRIPT_DIR}/omero-quota-enforcer.timer" "${timer_dst}"
    render_unit "${SCRIPT_DIR}/omero-quota-enforcer.path" "${path_dst}"

    "${SYSTEMCTL_BIN}" daemon-reload
    "${SYSTEMCTL_BIN}" reset-failed \
        omero-quota-enforcer.service \
        omero-quota-enforcer.timer \
        omero-quota-enforcer.path >/dev/null 2>&1 || true
    "${SYSTEMCTL_BIN}" enable omero-quota-enforcer.timer
    "${SYSTEMCTL_BIN}" start omero-quota-enforcer.timer
    "${SYSTEMCTL_BIN}" enable omero-quota-enforcer.path
    "${SYSTEMCTL_BIN}" start omero-quota-enforcer.path

    echo "  Installed and enabled: omero-quota-enforcer.timer (60s reconciliation)"
    echo "  Installed and enabled: omero-quota-enforcer.path  (inotify-triggered updates)"
}

write_marker_file() {
    local marker_file

    marker_file="${OMERO_DATA_DIR}/.admin-tools/quota-enforcer-installed"
    cat > "${marker_file}" <<MARKER
# This file is automatically written by install-quota-enforcer.sh.
# Its presence tells the omeroweb container that the host-side quota enforcer
# is installed and the Quotas tab in Admin Tools should be enabled.
# Do NOT delete this file unless you want to disable quota enforcement.
installed_at="$(date -Iseconds)"
omero_data_dir="${OMERO_DATA_DIR}"
MARKER
    echo "  Written: ${marker_file}"
}

main() {
omero_require_root

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

OMERO_DATA_DIR="$(omero_canonical_existing_dir "$1" "OMERO_DATA_DIR")"

echo "=== OMERO Quota Enforcer Installer ==="
echo ""
echo "OMERO data directory: ${OMERO_DATA_DIR}"
echo ""

echo "[1/7] Checking required packages..."
install_required_packages

echo "[2/7] Verifying ext4 project quota support..."
verify_project_quota_support

echo "[3/7] Installing enforcer script..."
install_enforcer_script

echo "[4/7] Creating configuration..."
write_defaults_file

echo "[5/7] Creating admin-tools directory..."
prepare_admin_tools_dir

echo "[6/7] Installing systemd units..."
install_systemd_units

echo "[7/7] Writing quota enforcer marker..."
write_marker_file

echo ""
echo "=== Installation complete ==="
echo ""
echo "The quota enforcer reacts to quota-state changes and reconciles every 60 seconds."
echo ""
echo "Useful commands:"
echo "  systemctl status omero-quota-enforcer.path     # Check file watcher status"
echo "  systemctl status omero-quota-enforcer.timer    # Check timer status"
echo "  journalctl -u omero-quota-enforcer.service     # View enforcement logs"
echo "  sudo ${enforcer_dst}  # Run manually"
echo ""
echo "To uninstall:"
echo "  sudo systemctl disable --now omero-quota-enforcer.timer omero-quota-enforcer.path"
echo "  sudo rm ${SYSTEMD_SYSTEM_DIR%/}/omero-quota-enforcer.{service,timer,path}"
echo "  sudo systemctl daemon-reload"
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main "$@"
fi
