apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # DevSkim: ignore DS137138 -- internal Docker network
    isDefault: true
    editable: false
