from typing import Any

class _Config:
    # Update. Inputs: *args, **kwargs. Output: None.
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    # Return a dynamic attribute. Inputs: name. Output: Any.
    def __getattr__(self, name: str) -> Any: ...

class Celery:
    conf: _Config

    # Create the typed stub object. Inputs: *args, **kwargs. Output: None.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    # Return autodiscover tasks. Inputs: *args, **kwargs. Output: Any.
    def autodiscover_tasks(self, *args: Any, **kwargs: Any) -> Any: ...
    # Return task. Inputs: *args, **kwargs. Output: Any.
    def task(self, *args: Any, **kwargs: Any) -> Any: ...
    # Return a dynamic attribute. Inputs: name. Output: Any.
    def __getattr__(self, name: str) -> Any: ...

# Return a dynamic attribute. Inputs: name. Output: Any.
def __getattr__(name: str) -> Any: ...
