from typing import Any

class _Config:
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Celery:
    conf: _Config

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def autodiscover_tasks(self, *args: Any, **kwargs: Any) -> Any: ...
    def task(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

def __getattr__(name: str) -> Any: ...
